---
- name: Playing around with regex
  hosts: localhost
  become: no
  vars:
    list_of_files_in_all_paths:
      - "Found file: /opt/patrol/bmcpp/Linux-2-6-x86-64/best1/24.2.00"
  tasks:

    - name: try Regex patters 1
      debug:
        msg: "{{ list_of_files_in_all_paths[0].path.split('/')[-1] | regex_search('[0-9]+\\.[0-9]+') }}"