---
- name: Delete files on a windows server
  hosts: localhost
  become: no
  vars_files:
    - vars.yml
  vars:
    list_of_files_in_all_paths:
      - "Found file: /opt/patrol/bmcpp/Linux-2-6-x86-64/best1/24.2.00"
  tasks:

    - name: Delete files
      debug:
        msg: "{{ Deleting file: {{ item.path.split('/')[-1] | regex_search('[0-9]+\\.[0-9]+') }}"
      loop: "{{ list_of_files_in_all_paths }}"